//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eletrobid.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EletrobidEntities : DbContext
    {
        public EletrobidEntities()
            : base("name=EletrobidEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EMPRESAORIGINARIA> EMPRESAORIGINARIAs { get; set; }
        public virtual DbSet<EMPRESAREVENDEDORA> EMPRESAREVENDEDORAs { get; set; }
        public virtual DbSet<IMPOSTO> IMPOSTOes { get; set; }
        public virtual DbSet<IMPOSTOPRODUTO> IMPOSTOPRODUTOes { get; set; }
        public virtual DbSet<PERFIL> PERFILs { get; set; }
        public virtual DbSet<PRODUTO> PRODUTOes { get; set; }
        public virtual DbSet<TIPOIMPOSTO> TIPOIMPOSTOes { get; set; }
        public virtual DbSet<TIPOPRODUTO> TIPOPRODUTOes { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
    }
}
