//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eletrobid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cidade
    {
        public int CidadeId { get; set; }
        public string Nome { get; set; }
        public Nullable<byte> EstadoId { get; set; }
        public bool Capital { get; set; }
        public string CodigoIbge { get; set; }
    
        public virtual Estado Estado { get; set; }
    }
}
