//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eletrobid.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EletrobidEntities : DbContext
    {
        public EletrobidEntities()
            : base("name=EletrobidEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmpresaOriginaria> EmpresaOriginarias { get; set; }
        public virtual DbSet<EmpresaRevendedora> EmpresaRevendedoras { get; set; }
        public virtual DbSet<Imposto> Impostoes { get; set; }
        public virtual DbSet<ImpostoProduto> ImpostoProdutoes { get; set; }
        public virtual DbSet<Perfil> Perfils { get; set; }
        public virtual DbSet<Produto> Produtoes { get; set; }
        public virtual DbSet<TipoImposto> TipoImpostoes { get; set; }
        public virtual DbSet<TipoProduto> TipoProdutoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
