//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eletrobid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESAREVENDEDORA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPRESAREVENDEDORA()
        {
            this.PRODUTOes = new HashSet<PRODUTO>();
        }
    
        public int IDEMPRESAREVENDEDORA { get; set; }
        public string RAZAOSOCIAL { get; set; }
        public string NOMEFANTASIA { get; set; }
        public string CNPJ { get; set; }
        public string TELEFONECONTATO1 { get; set; }
        public string TELEFONECONTATO2 { get; set; }
        public Nullable<double> MARGEMLUCRO { get; set; }
        public string ENDERECO { get; set; }
        public string CEP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO> PRODUTOes { get; set; }
    }
}
