//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eletrobid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPOSTOPRODUTO
    {
        public int IDIMPOSTOPRODUTO { get; set; }
        public int IDPRODUTO { get; set; }
        public int IDIMPOSTO { get; set; }
        public double VALORPAGAR { get; set; }
    
        public virtual IMPOSTO IMPOSTO { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
    }
}
