//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eletrobid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPOSTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMPOSTO()
        {
            this.IMPOSTOPRODUTOes = new HashSet<IMPOSTOPRODUTO>();
        }
    
        public int IDIMPOSTO { get; set; }
        public string NOME { get; set; }
        public int IDTIPOIMPOSTO { get; set; }
        public double VALOR { get; set; }
        public System.DateTime DATAINICIOCOBRANCA { get; set; }
        public string OBSERVACAO { get; set; }
    
        public virtual TIPOIMPOSTO TIPOIMPOSTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPOSTOPRODUTO> IMPOSTOPRODUTOes { get; set; }
    }
}
