//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eletrobid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imposto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Imposto()
        {
            this.ImpostoProduto = new HashSet<ImpostoProduto>();
        }
    
        public int IdImposto { get; set; }
        public string Nome { get; set; }
        public int IdTipoImposto { get; set; }
        public double Valor { get; set; }
        public System.DateTime DataInicioCobranca { get; set; }
        public string Observacao { get; set; }
    
        public virtual TipoImposto TipoImposto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImpostoProduto> ImpostoProduto { get; set; }
    }
}
