//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eletrobid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remessa
    {
        public int IdRemessa { get; set; }
        public int IdProduto { get; set; }
        public int IdEmpresaRecebedora { get; set; }
        public int IdNfeRemessa { get; set; }
        public int Quantidade { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Nfe Nfe { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
