//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eletrobid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        public int IdVenda { get; set; }
        public System.DateTime DataVenda { get; set; }
        public int ValorUnitarioVenda { get; set; }
        public int ValorTotalVenda { get; set; }
        public int CodigoReferenciaVenda { get; set; }
        public string ObservacaoVenda { get; set; }
        public int IdProduto { get; set; }
        public int QuantidadeVenda { get; set; }
        public int IdEmpresaRevendedora { get; set; }
        public Nullable<int> NumeroLote { get; set; }
        public bool Cancelada { get; set; }
        public Nullable<System.DateTime> DataCancelamento { get; set; }
        public string MotivoCancelamento { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
